// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniErp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniErp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniErp.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("audit_logs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("94000000-0000-0000-0000-000000000001"),
                            Action = "PurchaseOrderCreated",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Created approved demo purchase order PO-2026-002.",
                            EntityId = new Guid("90000000-0000-0000-0000-000000000003"),
                            EntityName = "PurchaseOrder",
                            PerformedAt = new DateTime(2026, 3, 22, 9, 30, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-0000-0000-000000000002"),
                            Action = "GoodsReceiptPosted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Received 4 task chairs against PO-2026-003.",
                            EntityId = new Guid("91000000-0000-0000-0000-000000000001"),
                            EntityName = "GoodsReceipt",
                            PerformedAt = new DateTime(2026, 3, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-0000-0000-000000000003"),
                            Action = "StockIssued",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Issued two filing cabinets for municipal office fit-out.",
                            EntityId = new Guid("92000000-0000-0000-0000-000000000002"),
                            EntityName = "InventoryTransaction",
                            PerformedAt = new DateTime(2026, 3, 29, 9, 15, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-0000-0000-000000000004"),
                            Action = "StockAdjusted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Recorded a damaged filing cabinet after inbound inspection.",
                            EntityId = new Guid("93000000-0000-0000-0000-000000000002"),
                            EntityName = "StockAdjustment",
                            PerformedAt = new DateTime(2026, 3, 30, 11, 0, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-0000-0000-000000000005"),
                            Action = "PurchaseOrderCreated",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Created approved demo purchase order PO-2026-006 for Eastlake Office Furnishings.",
                            EntityId = new Guid("90000000-0000-0000-0000-000000000011"),
                            EntityName = "PurchaseOrder",
                            PerformedAt = new DateTime(2026, 3, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-0000-0000-000000000006"),
                            Action = "GoodsReceiptPosted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Recorded rush replenishment receipt for mobile pedestals.",
                            EntityId = new Guid("92000000-0000-0000-0000-000000000005"),
                            EntityName = "InventoryTransaction",
                            PerformedAt = new DateTime(2026, 3, 31, 9, 30, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-0000-0000-000000000007"),
                            Action = "StockIssued",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Issued two task chairs for showroom refresh.",
                            EntityId = new Guid("92000000-0000-0000-0000-000000000006"),
                            EntityName = "InventoryTransaction",
                            PerformedAt = new DateTime(2026, 3, 31, 13, 20, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("94000000-0000-0000-0000-000000000008"),
                            Action = "StockAdjusted",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Cycle count increased conference table base inventory by two units.",
                            EntityId = new Guid("93000000-0000-0000-0000-000000000003"),
                            EntityName = "StockAdjustment",
                            PerformedAt = new DateTime(2026, 3, 31, 15, 5, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Seating"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Storage"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Components"
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("ReceivedByUserId");

                    b.ToTable("goods_receipts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("91000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000005"),
                            ReceiptNumber = "GR-2026-003",
                            ReceivedAt = new DateTime(2026, 3, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            ReceivedByUserId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("91000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000007"),
                            ReceiptNumber = "GR-2026-004",
                            ReceivedAt = new DateTime(2026, 3, 16, 10, 30, 0, 0, DateTimeKind.Utc),
                            ReceivedByUserId = new Guid("20000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PurchaseOrderLineId");

                    b.ToTable("goods_receipt_lines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("91000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GoodsReceiptId = new Guid("91000000-0000-0000-0000-000000000001"),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000001"),
                            PurchaseOrderLineId = new Guid("90000000-0000-0000-0000-000000000006"),
                            ReceivedQuantity = 4
                        },
                        new
                        {
                            Id = new Guid("91000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GoodsReceiptId = new Guid("91000000-0000-0000-0000-000000000003"),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000003"),
                            PurchaseOrderLineId = new Guid("90000000-0000-0000-0000-000000000008"),
                            ReceivedQuantity = 8
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ItemId", "WarehouseId", "LocationId")
                        .IsUnique();

                    b.ToTable("inventory_balances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000001"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            QuantityAvailable = 16,
                            QuantityOnHand = 18,
                            QuantityReserved = 2,
                            RowVersion = 0u,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000002"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            QuantityAvailable = 3,
                            QuantityOnHand = 4,
                            QuantityReserved = 1,
                            RowVersion = 0u,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000003"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            QuantityAvailable = 28,
                            QuantityOnHand = 32,
                            QuantityReserved = 4,
                            RowVersion = 0u,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000004"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            QuantityAvailable = 2,
                            QuantityOnHand = 5,
                            QuantityReserved = 3,
                            RowVersion = 0u,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000005"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            QuantityAvailable = 12,
                            QuantityOnHand = 14,
                            QuantityReserved = 2,
                            RowVersion = 0u,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000006"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            QuantityAvailable = 10,
                            QuantityOnHand = 11,
                            QuantityReserved = 1,
                            RowVersion = 0u,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("inventory_transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("92000000-0000-0000-0000-000000000001"),
                            BalanceAfter = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000001"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000002"),
                            QuantityChange = 4,
                            ReferenceId = new Guid("91000000-0000-0000-0000-000000000001"),
                            ReferenceType = "GoodsReceipt",
                            TransactionType = 1,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("92000000-0000-0000-0000-000000000002"),
                            BalanceAfter = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000002"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 29, 9, 15, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000002"),
                            QuantityChange = -2,
                            Reason = "Reserved for municipal office fit-out",
                            ReferenceType = "ManualIssue",
                            TransactionType = 2,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("92000000-0000-0000-0000-000000000003"),
                            BalanceAfter = 32,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000003"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 30, 8, 45, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            QuantityChange = 3,
                            Reason = "Cycle count found extra kit components",
                            ReferenceId = new Guid("93000000-0000-0000-0000-000000000001"),
                            ReferenceType = "StockAdjustment",
                            TransactionType = 3,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("92000000-0000-0000-0000-000000000004"),
                            BalanceAfter = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000002"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 30, 11, 0, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            QuantityChange = -1,
                            Reason = "One cabinet damaged in transit",
                            ReferenceId = new Guid("93000000-0000-0000-0000-000000000002"),
                            ReferenceType = "StockAdjustment",
                            TransactionType = 4,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("92000000-0000-0000-0000-000000000005"),
                            BalanceAfter = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000005"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 31, 9, 30, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000002"),
                            QuantityChange = 6,
                            Reason = "Rush replenishment for mobile pedestals",
                            ReferenceId = new Guid("90000000-0000-0000-0000-000000000011"),
                            ReferenceType = "VendorDelivery",
                            TransactionType = 1,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("92000000-0000-0000-0000-000000000006"),
                            BalanceAfter = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000001"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 31, 13, 20, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000002"),
                            QuantityChange = -2,
                            Reason = "Moved chairs to showroom staging area",
                            ReferenceType = "ShowroomRefresh",
                            TransactionType = 2,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("92000000-0000-0000-0000-000000000007"),
                            BalanceAfter = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000006"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 31, 15, 5, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            QuantityChange = 2,
                            Reason = "Found two extra conference table bases during cycle count",
                            ReferenceId = new Guid("93000000-0000-0000-0000-000000000003"),
                            ReferenceType = "StockAdjustment",
                            TransactionType = 3,
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("StandardCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable office task chair",
                            IsActive = true,
                            Name = "Task Chair",
                            ReorderLevel = 10,
                            Sku = "CHR-1001",
                            StandardCost = 129.99m,
                            Unit = "EA"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Three-drawer steel filing cabinet",
                            IsActive = true,
                            Name = "Filing Cabinet",
                            ReorderLevel = 5,
                            Sku = "CAB-2001",
                            StandardCost = 249.00m,
                            Unit = "EA"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set of four metal desk legs",
                            IsActive = true,
                            Name = "Desk Leg Kit",
                            ReorderLevel = 20,
                            Sku = "KIT-3001",
                            StandardCost = 58.50m,
                            Unit = "SET"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft seating lounge chair for waiting areas",
                            IsActive = true,
                            Name = "Lounge Chair",
                            ReorderLevel = 6,
                            Sku = "LNG-4001",
                            StandardCost = 219.00m,
                            Unit = "EA"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lockable under-desk storage pedestal",
                            IsActive = true,
                            Name = "Mobile Pedestal",
                            ReorderLevel = 8,
                            Sku = "PED-5001",
                            StandardCost = 179.00m,
                            Unit = "EA"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Powder-coated steel base for conference tables",
                            IsActive = true,
                            Name = "Conference Table Base",
                            ReorderLevel = 4,
                            Sku = "BAS-6001",
                            StandardCost = 84.00m,
                            Unit = "EA"
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.ToTable("locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Code = "A1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Aisle A1",
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExpectedDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PoNumber = "PO-2026-001",
                            Status = 1,
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExpectedDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            PoNumber = "PO-2026-002",
                            Status = 2,
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExpectedDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            PoNumber = "PO-2026-003",
                            Status = 3,
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExpectedDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PoNumber = "PO-2026-004",
                            Status = 4,
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExpectedDate = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            PoNumber = "PO-2026-005",
                            Status = 5,
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExpectedDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            PoNumber = "PO-2026-006",
                            Status = 2,
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("purchase_order_lines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000002"),
                            OrderedQuantity = 6,
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000001"),
                            ReceivedQuantity = 0,
                            UnitCost = 235.00m
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000004"),
                            OrderedQuantity = 4,
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000001"),
                            ReceivedQuantity = 0,
                            UnitCost = 210.00m
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000003"),
                            OrderedQuantity = 12,
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000003"),
                            ReceivedQuantity = 0,
                            UnitCost = 54.75m
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000006"),
                            OrderedQuantity = 6,
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000003"),
                            ReceivedQuantity = 0,
                            UnitCost = 84.00m
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000001"),
                            OrderedQuantity = 10,
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000005"),
                            ReceivedQuantity = 4,
                            UnitCost = 121.50m
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000003"),
                            OrderedQuantity = 8,
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000007"),
                            ReceivedQuantity = 8,
                            UnitCost = 52.00m
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000001"),
                            OrderedQuantity = 3,
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000009"),
                            ReceivedQuantity = 0,
                            UnitCost = 125.00m
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000005"),
                            OrderedQuantity = 10,
                            PurchaseOrderId = new Guid("90000000-0000-0000-0000-000000000011"),
                            ReceivedQuantity = 0,
                            UnitCost = 176.50m
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "InventoryManager"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "WarehouseStaff"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("stock_adjustments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("93000000-0000-0000-0000-000000000001"),
                            AdjustmentType = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000003"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 30, 8, 45, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            QuantityDelta = 3,
                            Reason = "Cycle count found extra kit components",
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("93000000-0000-0000-0000-000000000002"),
                            AdjustmentType = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000002"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 30, 11, 0, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            QuantityDelta = 1,
                            Reason = "One cabinet damaged in transit",
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("93000000-0000-0000-0000-000000000003"),
                            AdjustmentType = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000006"),
                            LocationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PerformedAt = new DateTime(2026, 3, 31, 15, 5, 0, 0, DateTimeKind.Utc),
                            PerformedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            QuantityDelta = 2,
                            Reason = "Found two extra conference table bases during cycle count",
                            WarehouseId = new Guid("50000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            ContactName = "Jordan Lee",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "orders@acme-industrial.example",
                            IsActive = true,
                            Name = "Acme Industrial Supply",
                            Phone = "555-0100"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            ContactName = "Taylor Smith",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sales@northwood.example",
                            IsActive = true,
                            Name = "Northwood Components",
                            Phone = "555-0110"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            ContactName = "Morgan Patel",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "account-team@eastlake.example",
                            IsActive = true,
                            Name = "Eastlake Office Furnishings",
                            Phone = "555-0120"
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.SupplierItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierSku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SupplierId", "ItemId")
                        .IsUnique();

                    b.ToTable("supplier_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000001"),
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000001"),
                            SupplierSku = "ACME-CHR-1001"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000002"),
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000001"),
                            SupplierSku = "ACME-CAB-2001"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000003"),
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000002"),
                            SupplierSku = "NW-KIT-3001"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000004"),
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000003"),
                            SupplierSku = "EL-LNG-4001"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000005"),
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000003"),
                            SupplierSku = "EL-PED-5001"
                        },
                        new
                        {
                            Id = new Guid("71000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("70000000-0000-0000-0000-000000000006"),
                            SupplierId = new Guid("40000000-0000-0000-0000-000000000002"),
                            SupplierSku = "NW-BAS-6001"
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@minierp.local",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "100000.D7/na2fAshvnIG4dYnDY3w==.r1Wxdl0Svjd+hM1EFn3gwvocm0IuZvGY0HTcOEAuGUM="
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "warehouse@minierp.local",
                            FullName = "Warehouse Operator",
                            IsActive = true,
                            PasswordHash = "100000.yjJgxVnzj85lVCaN8of6NA==.NTw4Z2FymPSWFp5BzyaC8J1F9NpH6x8el2ST+FgofYE="
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            UserId = new Guid("20000000-0000-0000-0000-000000000002"),
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Code = "MAIN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Main Warehouse"
                        });
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.User", "ReceivedByUser")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("ReceivedByUser");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Item", "Item")
                        .WithMany("GoodsReceiptLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany("GoodsReceiptLines")
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrderLine");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.InventoryBalance", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.Item", "Item")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Location", "Location")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.Item", "Item")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Location", "Location")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.User", "PerformedByUser")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");

                    b.Navigation("PerformedByUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Item", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Location", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.User", "CreatedByUser")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.Item", "Item")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.StockAdjustment", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.Item", "Item")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Location", "Location")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.User", "PerformedByUser")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");

                    b.Navigation("PerformedByUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.SupplierItem", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.Item", "Item")
                        .WithMany("SupplierItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.Supplier", "Supplier")
                        .WithMany("SupplierItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("MiniErp.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniErp.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Item", b =>
                {
                    b.Navigation("GoodsReceiptLines");

                    b.Navigation("InventoryBalances");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("PurchaseOrderLines");

                    b.Navigation("StockAdjustments");

                    b.Navigation("SupplierItems");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Location", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("StockAdjustments");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Navigation("GoodsReceiptLines");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");

                    b.Navigation("SupplierItems");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("GoodsReceipts");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("StockAdjustments");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MiniErp.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("Locations");

                    b.Navigation("StockAdjustments");
                });
#pragma warning restore 612, 618
        }
    }
}
